version: '3.8'

services:
  logger:
    build:
      context: .
      dockerfile: crypto_stream/logger/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  flink:
    build:
      context: .
      dockerfile: crypto_stream/flink/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - logger
    environment:
      - LOGGER_URL=http://logger:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka:
    build:
      context: .
      dockerfile: crypto_stream/kafka/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - logger
    environment:
      - LOGGER_URL=http://logger:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build:
      context: .
      dockerfile: crypto_stream/streamlit/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - logger
    environment:
      - LOGGER_URL=http://logger:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  logs:
