apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-service
  labels:
    app: flink-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-service
  template:
    metadata:
      labels:
        app: flink-service
    spec:
      containers:
      - name: flink-service
        image: crypto-stream-flink:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: FLINK_STATE_BACKEND
          value: "filesystem"
        - name: FLINK_CHECKPOINTS_DIRECTORY
          value: "/opt/flink/state"
        volumeMounts:
        - name: flink-state
          mountPath: /opt/flink/state
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: flink-state
        persistentVolumeClaim:
          claimName: flink-state-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flink-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: flink-service
