LOGGER_URL = "http://logger-service:8000"
FLINK_URL = "http://flink-service:8001"
KAFKA_URL = "http://kafka-service:8002"
KAFKA_BOOTSTRAP_SERVERS = "kafka-broker:9092"
STREAMLIT_URL = "http://streamlit-service:8003"
